// The label a header pin's text carries before " -- run: `...`" -- "HEAD" or
// "revision" out of compose.mjs's own draft text. Used only to name which
// pin a BLOCKED note (below) is talking about; falls back to the whole text
// if the shape is ever unrecognized rather than throwing.
function headerPinLabel(text) {
  const m = text.match(/^(.*?)\s+—\s+run:/);
  return m ? m[1].trim() : text;
}

// Everything that goes into a rendered note passes through here first.
//
// Two jobs, both from the 2026-08-14 whole-branch review. Raw stderr is
// multi-line, and interpolating it into a single-line italic run or a
// blockquote paragraph broke the markup outright -- in the header case the
// continuation lines landed OUTSIDE the blockquote, in the one document
// whose entire job is reading as honest. And a note must never register as
// a new claim, which is a property of its characters: extract.mjs's
// PREAMBLE_PATTERNS only matches `**bold**` and `` `backtick` `` spans, so
// a note carrying neither is visible prose to a reader and invisible to the
// scanner. An error message can carry either, so both come off here rather
// than being assumed absent.
function plainly(text) {
  return String(text ?? '')
    .replace(/`/g, "'")
    .replace(/\*/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

// The sentence a non-PASS birth check renders as, in the header's
// blockquote and in a section body alike. FAIL and BLOCKED are different
// facts and get different words: BLOCKED means the check could not run,
// FAIL means it ran and the claim did not hold.
function verdictPhrase(verdict) {
  if (verdict === 'BLOCKED') return 'could not be verified at generation time';
  if (verdict === 'FAIL') return 'was checked at generation time and did not hold';
  return `${String(verdict).toLowerCase()} at generation time`;
}

// Review fix 1 (2026-08-14): the intro three lines up claims "every claim
// below was verified at the moment it was written." A BLOCKED pin makes
// that sentence false unless something on the page contradicts it -- and
// this is reachable today, not hypothetically: the one wired HEAD pin
// BLOCKs whenever there is no git binary, the target isn't a checkout, or
// the sandbox forbids exec. Rendered as its own blockquote paragraph, blank
// `>` before it, run through plainly() so it stays one line and carries no
// span the extractor would read as a claim.
function headerVerdictNote(draft) {
  return plainly(`${headerPinLabel(draft.text)} ${verdictPhrase(draft.verdict)}: ${draft.evidence ?? ''}`);
}

// Controller correction 1: the header section's drafts render as a
// blockquote list, not bare lines under a heading. extractClaims's preamble
// reader only sees the run of `>`-prefixed lines before the document's first
// `##` heading -- a bare "HEAD -- run: `...`" line under a heading is none of
// marker-tagged, preamble, or prose-expectation, so it would never round-trip
// back into a claim. `> - <text>` inside the leading blockquote is the exact
// shape the preamble reader already walks (see
// tests/fixtures/star-smoke-remediated.md's own remediated pins).
//
// Review fix 2 (2026-08-14): each bullet gets its own blockquote paragraph
// (blank `>` between them), not one shared paragraph. extractClaims's
// preamble builder only breaks a paragraph on a blank blockquote line, so
// two bullets with no separator joined into a single claim string on
// read-back -- and SELF_ANSWERING_RE has no /g flag, so re-verifying that
// joined claim would only ever run the FIRST pin's command. Any second
// header pin would become permanently unverifiable prose the moment it
// round-tripped once. The separator makes each bullet extract as its own
// claim, each carrying (and later re-running) only its own command.
function renderHeaderIntro({ generatedFrom, header }) {
  const lines = [
    `> Generated by vibe-runbook from: ${generatedFrom.join(', ')}.`,
    // Review, coordinator round: "every claim below was verified" overstated
    // it -- a BLOCKED pin renders its own evidence note right beneath it
    // (see headerVerdictNote below), so the document isn't silent about a
    // failed check, but the blanket sentence still read as if none existed.
    '> Claims were checked when this was written; any that could not be are marked below.',
    '> Pins name the command that answers them, so they cannot go stale.',
  ];
  if (!header || header.drafts.length === 0) return lines;

  lines.push('>');
  header.drafts.forEach((d, i) => {
    if (i > 0) lines.push('>');
    lines.push(`> - ${d.text}`);
  });

  const blocked = header.drafts.filter((d) => d.verdict && d.verdict !== 'PASS');
  for (const d of blocked) lines.push('>', `> ${headerVerdictNote(d)}`);

  return lines;
}

// A non-header section's drafts, stubs, and notes render under their own
// heading: a draft's own marker (**Right:**, a bare `run:` pin, ordinary step
// prose) carries it as a claim or leaves it as non-claim prose on its own; a
// bad verdict gets a visible prose note beneath it; a stub becomes a
// **Unwritten:** line findStubs already recognizes; a note becomes a
// *Not gathered: ...* line.
//
// Review fix (2026-08-14, whole-branch): that note used to be an HTML
// comment -- `<!-- BLOCKED at generation: ... -->` -- which does not render.
// On GitHub, or in any preview, the section read as a bare confident claim
// that the endpoint answers 200, written at the exact moment the tool knew
// it could not confirm that. This is the same constraint renderHeaderIntro
// above already honors twenty lines up, so it now uses the same words and
// the same plainly() guard: visible to a reader, invisible to the scanner.
//
// Review fix 3 (2026-08-14, from the brief, not the controller): a blank
// line always separates the draft's own text from its verdict comment.
// Without it, groupIntoUnits joins the comment line into the SAME unit as
// the draft (no blank line, no heading, no blockquote, no list/table start
// to break it) -- so on read-back the comment text ends up glued inside
// claim.text. It still classified correctly either way, but remediate.mjs
// matches claim.text byte-for-byte against the file to apply a rewrite, and
// a claim carrying trailing comment junk is a fragile base for that match.
function renderSectionBody(section) {
  const out = [`## ${section.title}`, ''];
  for (const d of section.drafts) {
    out.push(d.text, '');
    if (d.verdict && d.verdict !== 'PASS') {
      out.push(plainly(`This claim ${verdictPhrase(d.verdict)}: ${d.evidence ?? ''}`), '');
    }
  }
  for (const q of section.stubs) out.push(`**Unwritten:** ${q}`, '');
  for (const n of section.notes) out.push(`*Not gathered: ${plainly(n)}*`, '');
  return out;
}

// Controller correction 2: compose() can append a `gaps` section after the
// seven fixed SECTIONS entries -- do not assume the array is exactly
// SECTIONS.length. Iterating whatever `sections` actually holds (rather than
// a hardcoded list of ids) means an appended gaps section renders for free
// through the same generic path every other section uses.
export function emitRunbook({ appName, sections, generatedFrom }) {
  const header = sections.find((s) => s.id === 'header');
  const rest = sections.filter((s) => s.id !== 'header');

  const out = [];
  out.push(`# Runbook — ${appName}`, '');
  out.push(...renderHeaderIntro({ generatedFrom, header }), '');

  // The header's drafts already went into the leading blockquote above. If
  // it also carries stubs or notes (gaps must reach the page even when a
  // draft exists for the same section, per the given test fixture), give it
  // its own heading too -- but never repeat its drafts.
  if (header && (header.stubs.length > 0 || header.notes.length > 0)) {
    out.push(`## ${header.title}`, '');
    for (const q of header.stubs) out.push(`**Unwritten:** ${q}`, '');
    for (const n of header.notes) out.push(`*Not gathered: ${plainly(n)}*`, '');
  }

  for (const s of rest) {
    if (s.drafts.length === 0 && s.stubs.length === 0 && s.notes.length === 0) continue;
    out.push(...renderSectionBody(s));
  }

  return out.join('\n');
}
