// Controller correction 1: the header section's drafts render as a
// blockquote list, not bare lines under a heading. extractClaims's preamble
// reader only sees the run of `>`-prefixed lines before the document's first
// `##` heading -- a bare "HEAD -- run: `...`" line under a heading is none of
// marker-tagged, preamble, or prose-expectation, so it would never round-trip
// back into a claim. `> - <text>` inside the leading blockquote is the exact
// shape the preamble reader already walks (see
// tests/fixtures/star-smoke-remediated.md's own remediated pins).
function renderHeaderIntro({ generatedFrom, header }) {
  const lines = [
    `> Generated by vibe-runbook from: ${generatedFrom.join(', ')}.`,
    '> Every claim below was verified at the moment it was written.',
    '> Pins name the command that answers them, so they cannot go stale.',
  ];
  if (header && header.drafts.length > 0) {
    lines.push('>');
    for (const d of header.drafts) lines.push(`> - ${d.text}`);
  }
  return lines;
}

// A non-header section's drafts, stubs, and notes render under their own
// heading, unchanged from the original shape: a draft's own marker
// (**Right:**, a bare `run:` pin, ordinary step prose) carries it as a claim
// or leaves it as non-claim prose on its own; a bad verdict gets an inline
// HTML-comment annotation; a stub becomes a **Unwritten:** line findStubs
// already recognizes; a note becomes a *Not gathered: ...* line.
function renderSectionBody(section) {
  const out = [`## ${section.title}`, ''];
  for (const d of section.drafts) {
    out.push(d.text);
    if (d.verdict && d.verdict !== 'PASS') {
      out.push(`  <!-- ${d.verdict} at generation: ${d.evidence ?? ''} -->`);
    }
    out.push('');
  }
  for (const q of section.stubs) out.push(`**Unwritten:** ${q}`, '');
  for (const n of section.notes) out.push(`*Not gathered: ${n}*`, '');
  return out;
}

// Controller correction 2: compose() can append a `gaps` section after the
// seven fixed SECTIONS entries -- do not assume the array is exactly
// SECTIONS.length. Iterating whatever `sections` actually holds (rather than
// a hardcoded list of ids) means an appended gaps section renders for free
// through the same generic path every other section uses.
export function emitRunbook({ appName, sections, generatedFrom }) {
  const header = sections.find((s) => s.id === 'header');
  const rest = sections.filter((s) => s.id !== 'header');

  const out = [];
  out.push(`# Runbook — ${appName}`, '');
  out.push(...renderHeaderIntro({ generatedFrom, header }), '');

  // The header's drafts already went into the leading blockquote above. If
  // it also carries stubs or notes (gaps must reach the page even when a
  // draft exists for the same section, per the given test fixture), give it
  // its own heading too -- but never repeat its drafts.
  if (header && (header.stubs.length > 0 || header.notes.length > 0)) {
    out.push(`## ${header.title}`, '');
    for (const q of header.stubs) out.push(`**Unwritten:** ${q}`, '');
    for (const n of header.notes) out.push(`*Not gathered: ${n}*`, '');
  }

  for (const s of rest) {
    if (s.drafts.length === 0 && s.stubs.length === 0 && s.notes.length === 0) continue;
    out.push(...renderSectionBody(s));
  }

  return out.join('\n');
}
